__default__:
  memory: "{resources.mem_mb}"
  n: 1
  name: "{rule}.{wildcards}"
  queue: short
  outfile: "{log}"
#Â 00_1_common.smk
create_F1_samples_file:
  queue: datamover
create_F2_samples_file:
  queue: datamover
# 02_1_F0_mapping.smk
bwa_mem2_mem_F0:
  n: "{threads}"
# 03_1_F1_mapping.smk
copy_F1_seq_data:
  queue: datamover
bwa_mem2_mem_F1:
  n: "{threads}"
# 04_F2_mapping.smk
copy_F2_seq_data:
  queue: datamover
bwa_mem2_mem_F2:
  n: "{threads}"
# 05_F2_recomb_blocks.smk
consolidate_dbABs_Ewan:
  queue: bigmem
filter_sites_for_read_count_and_cab_prop:
  queue: bigmem
# 07_3_GCTA.smk
run_mlma_loco:
  n: "{threads}"

