__default__:
  memory: 5000
  n: 1
  name: "{rule}.{wildcards}"
  queue: "standard"
  outfile: "{log}"
# 01_ref.smk
bwa_mem2_index:
  memory: "{resources.mem_mb}"
# 02_F0_mapping.smk
map_reads_F0:
  memory: "{resources.mem_mb}"
  n: "{threads}"
replace_rg_F0:
  memory: "{resources.mem_mb}"
sort_sam_F0:
  memory: "{resources.mem_mb}"
mark_duplicates_F0:
  memory: "{resources.mem_mb}"
# 03_F0_calling.smk
haplotype_caller:
  memory: "{resources.mem_mb}"
# 04_F2_mapping.smk
copy_f2_seq_data:
  queue: "datamover"
bwa_mem2_mem:
  memory: "{resources.mem_mb}"
  n: "{threads}"
sort_sam_f2:
  memory: "{resources.mem_mb}"
# 05_F2_recomb_blocks.smk
bam_readcount_F2_all:
  memory: "{resources.mem_mb}"
bam_readcount_F2_excl_repeat_sites:
  memory: "{resources.mem_mb}"
bam_readcount_F2_excl_repeat_reads:
  memory: "{resources.mem_mb}"
make_dp_AB_F2:
  memory: "{resources.mem_mb}"
run_rc_block_F2:
  memory: "{resources.mem_mb}"
# 06_F0_recomb_blocks.smk
make_dp_AB_F0:
  memory: "{resources.mem_mb}"  
run_rc_block_F0:
  memory: "{resources.mem_mb}"
# 07_association_testing.smk
create_gwas_input:
  memory: "{resources.mem_mb}"
test_gwls:
  memory: "{resources.mem_mb}"
run_gwls:
  memory: "{resources.mem_mb}"
run_permutations:
  memory: "{resources.mem_mb}"