__default__:
  memory: "{resources.mem_mb}"
  n: 1
  name: "{rule}.{wildcards}"
  queue: standard
  outfile: "{log}"
#Â 00_1_common.smk
create_F1_samples_file:
  queue: datamover
create_F2_samples_file:
  queue: datamover
# 02_F0_mapping.smk
map_reads_F0:
  n: "{threads}"
# 03_1_F1_mapping.smk
copy_F1_seq_data:
  queue: datamover
bwa_mem2_mem_F1:
  n: "{threads}"
# 04_F2_mapping.smk
copy_f2_seq_data:
  queue: datamover
bwa_mem2_mem:
  n: "{threads}"
# 05_F2_recomb_blocks.smk
consolidate_dbABs_Ewan:
  queue: bigmem
filter_sites_for_read_count_and_cab_prop:
  queue: bigmem
# 07_association_testing.smk
run_gwls:
  queue: "{resources.queue}"
run_permutations:
  queue: "{resources.queue}"

