####################
# Config files
####################
F0_samples:
    config/F0_samples.txt
# To ensure that they remain in the right order for certain rules, e.g. `get_divergent_sites`:
F0_lines: 
    - Cab
    - Kaga
F2_samples:
    config/F2_samples.txt
F2_valid_lanes:
    config/F2_valid_lanes.txt
####################
# Parameters
####################
pairs:
    - 1
    - 2
contigs:
    - 1
    - 24
ref:
    # ensembl species name
    species: oryzias_latipes
    # ensembl release
    release: 104
    # genome build
    build: ASM223467v1
bin_length:
    - 5000
    - 10000
    - 15000
    - 20000
bin_length_F0:
    - 5000
    - 100000
####################
# Locations
####################
ref_prefix:
    /hps/nobackup/birney/users/ian/somites/refs/hdrr
raw_data_dir:
    /nfs/research/birney/projects/indigene/raw_data/Ali
working_dir:
    /hps/nobackup/birney/users/ian/somites
tmp_dir:
    /hps/nobackup/birney/users/ian/somites/tmp
data_store_dir:
    /nfs/research/birney/users/ian/somites
####################
# Containers
####################
minimap2:
    docker://quay.io/biocontainers/minimap2:2.21--h5bf99c6_0
bwa-mem2:
    docker://quay.io/biocontainers/bwa-mem2:2.2.1--he513fc3_0
picard:
    docker://quay.io/biocontainers/picard:2.9.2--2
gatk:
    docker://quay.io/biocontainers/gatk4:4.2.0.0--0
samtools:
    docker://quay.io/biocontainers/samtools:1.13--h8c37831_0
bcftools:
    docker://biocontainers/bcftools:v1.9-1-deb_cv1
pandas:
    docker://quay.io/biocontainers/pandas:1.1.5
bam-readcount:
    docker://quay.io/biocontainers/bam-readcount:0.8--py36pl526h94a8ba4_4
R:
    docker://brettellebi/somite_f2:latest


