####################
# Locations
####################
ref_prefix:
    /hps/nobackup/birney/users/ian/somites/refs/hdrr
F1_sequence_dirs:
    - /nfs/ftp/private/indigene_ftp/upload/Ali/F1_Kaga-Cab_DeepSeq
F2_sequence_dirs:
    - /nfs/ftp/private/indigene_ftp/upload/Ali/Kaga-Cab_F2_First200WGS
    - /nfs/ftp/private/indigene_ftp/upload/Ali/Kaga-Cab_F2_Fish201-400_WGS
    - /nfs/ftp/private/indigene_ftp/upload/Ali/Kaga-Cab_F2_Fish401-595_WGS
    - /nfs/ftp/private/indigene_ftp/upload/Ali/Kaga-Cab_F2_Fish596-648_WGS
tmp_dir:
    /hps/nobackup/birney/users/ian/somites/tmp
working_dir:
    /hps/nobackup/birney/users/ian/somites
data_store_dir:
    /nfs/research/birney/users/ian/somites
####################
# Config files
####################
F0_samples:
    config/F0_samples.txt
# To ensure that they remain in the right order for certain rules, e.g. `get_divergent_sites`:
F0_lines: 
    - Cab
    - Kaga
F1_samples:
    config/F1_samples.txt
F2_samples:
    config/F2_samples.txt
F2_valid_lanes:
    config/F2_valid_lanes.txt
hdrr_repeats_gff:
    /nfs/research/birney/users/ian/mikk_genome/repeats/medaka_hdrr_repeats.fixed.gff
phenotypes_file:
    #data/First595-F2_DF_removed393-389-121_outliers.xlsx
    #data/20220214_phenotypes.xlsx
    data/20220321_phenotypes.xlsx # now includes reporter
target_phenotypes:
    - intercept
    #- mean
    - unsegmented_psm_area
ref_chr_lengths:
    data/Oryzias_latipes.ASM223467v1.dna.toplevel.fa_chr_counts.txt
het_black_list:
    data/20200716_mikk_panel_proportion_het_across_genome.txt
####################
# Parameters
####################
pairs:
    - 1
    - 2
contigs:
    - 1
    - 24
ref:
    # ensembl species name
    species: oryzias_latipes
    # ensembl release
    release: 104
    # genome build
    build: ASM223467v1
min_reads:
    100
max_reads:
    10000
min_prop_cab:
    0.2
max_prop_cab:
    0.8
low_cov_samples:
    - 26
    - 89
    - 166
    - 178
    - 189
    - 227
    - 239
    - 470
    - 472
    - 473
    - 490
    - 501
    - 502
    - 503
    - 504
    - 505
    - 506
    - 507
    - 508
    - 509
    - 510
    - 511
site_filter:
    - all_sites
    #- no_repeat_sites
    #- no_repeat_reads
    #- no_repeat_reads_or_pers_hets
    - no_repeat_reads_or_pers_hets_filtered_for_read_count_and_cab_prop
bin_length:
    - 5000
    #- 10000
    #- 15000
    - 20000
reduced_formula:
    - "~0"
    - "~1"
bin_length_F0:
    - 5000
    - 100000
n_sample_gts:
    - 10
covariates:
    - None
    - Microscope
    - Microscope-reporter_pheno
    #- Date_of_imaging
    #- Microscope-Date_of_imaging
inverse_norm:
    - "TRUE"
    - "FALSE"
n_permutations:
    - 10
####################
# Containers
####################
minimap2:
    docker://quay.io/biocontainers/minimap2:2.21--h5bf99c6_0
bwa-mem2:
    docker://quay.io/biocontainers/bwa-mem2:2.2.1--he513fc3_0
picard:
    docker://quay.io/biocontainers/picard:2.9.2--2
gatk:
    docker://quay.io/biocontainers/gatk4:4.2.0.0--0
samtools:
    docker://quay.io/biocontainers/samtools:1.13--h8c37831_0
bcftools:
    docker://biocontainers/bcftools:v1.9-1-deb_cv1
pandas:
    docker://quay.io/biocontainers/pandas:1.1.5
bam-readcount:
    docker://quay.io/biocontainers/bam-readcount:0.8--py36pl526h94a8ba4_4
R:
    /hps/nobackup/birney/users/ian/containers/somites/R_4.1.0.sif
PhenotypeSimulator:
    /hps/nobackup/birney/users/ian/containers/somites/R_4.1.0_PhenotypeSimulator.sif
tidyverse_4:
    /hps/nobackup/birney/users/ian/containers/somites/rocker_tidyverse_4.1.2.sif
java:
    docker://openjdk:7-slim
perl:
    docker://perl:5.34.0-slim
hmmlearn:
    /hps/nobackup/birney/users/ian/containers/somites/hmmlearn_0.2.7.sif


